config/routes.rb
Rails.application.routes.draw do

  resources :donations
  devise_for :users

  root 'static#home'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
    after_create :send_email
    
    def send_email
        Mailer.thank_donor(self).deliver
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:name, :email, :street, :city, :state, :zip, :amount, :chapter)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :chapter %><br>
    <%= f.text_field :chapter, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-default btn-lg' %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Donations</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Amount</th>
      <th>Chapter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.name %></td>
        <td><%= donation.email %></td>
        <td><%= donation.street %></td>
        <td><%= donation.city %></td>
        <td><%= donation.state %></td>
        <td><%= donation.zip %></td>
        <td><%= donation.amount %></td>
        <td><%= donation.chapter %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>Add New Donation</h1>
<p>Please note that a thank you email will be sent to the entered email</p>
<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @donation.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donation.email %>
</p>

<p>
  <strong>Street:</strong>
  <%= @donation.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @donation.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @donation.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @donation.zip %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @donation.amount %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @donation.chapter %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "alert alert-{key}" %>
<% end %>
<%=image_tag 'wwcLogo.png'%>

<div class='container'>
  <%= yield %>
</div>

</body>
</html>